alias: Alarm Controler
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel. # TODO: Set Alarm entity
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel. # TODO: Set Alarm entity
        state: triggered
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: alarm_control_panel. # TODO: Set Alarm entity
            state: arming
        sequence:
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: alarm_control_panel. # TODO: Set Alarm entity
                    attribute: next_state
                    state: armed_custom_bypass
            then:
              - action: timer.start
                metadata: {}
                data:
                  duration: "00:01"
                target:
                  entity_id: timer. # TODO: Set Timer helper entity
      - conditions:
          - condition: state
            entity_id: alarm_control_panel. # TODO: Set Alarm entity
            state: disarmed
        sequence:
          - action: timer.finish
            metadata: {}
            data: {}
            target:
              entity_id: timer. # TODO: Set Timer helper entity
            # TODO: Add actions for when disarmed
      - conditions:
          - condition: state
            entity_id: alarm_control_panel. # TODO: Set Alarm entity
            state: armed_home
        sequence:
          - action: timer.finish
            metadata: {}
            data: {}
            target:
              entity_id: timer. # TODO: Set Timer helper entity
            # TODO: Add actions for when arming finishes and armed to this mode
          - repeat:
              sequence: []
              while:
                - condition: not
                  conditions:
                    - condition: state
                      entity_id: alarm_control_panel. # TODO: Set Alarm entity
                      state: triggered
            # TODO: Add actions for when alarm is trigered when in this mode
      - conditions:
          - condition: state
            entity_id: alarm_control_panel. # TODO: Set Alarm entity
            state: armed_away
        sequence:
          - action: timer.finish
            metadata: {}
            data: {}
            target:
              entity_id: timer. # TODO: Set Timer helper entity
            # TODO: Add actions for when arming finishes and armed to this mode
          - repeat:
              sequence: []
              while:
                - condition: not
                  conditions:
                    - condition: state
                      entity_id: alarm_control_panel. # TODO: Set Alarm entity
                      state: triggered
            # TODO: Add actions for when alarm is trigered when in this mode
      - conditions:
          - condition: state
            entity_id: alarm_control_panel. # TODO: Set Alarm entity
            state: armed_custom_bypass
        sequence:
          - action: timer.finish
            metadata: {}
            data: {}
            target:
              entity_id: timer. # TODO: Set Timer helper entity
            # TODO: Add actions for when arming finishes and armed to this mode
          - repeat:
              sequence: []
              while:
                - condition: not
                  conditions:
                    - condition: state
                      entity_id: alarm_control_panel. # TODO: Set Alarm entity
                      state: triggered
            # TODO: Add actions for when alarm is trigered when in this mode
mode: restart
